### PR TITLE
:sparkles: - Show the path of the depency cycle

### PR DESCRIPTION
**Pull request by jfrolich**

### CODE REVIEW

**Comment by jfrolich** [comment]
Current dependencies on/for this PR:
* master
  * **PR #55** <a href="https://app.graphite.dev/github/pr/rolandpeelen/rewatch/55" target="_blank">Graphite</a> 
    * **PR #56** <a href="https://app.graphite.dev/github/pr/rolandpeelen/rewatch/56" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/rolandpeelen/rewatch/56?utm_source=stack-comment).

**Comment by zth** [comment]
Maybe this doesn't apply, but could this error be written in the same format that the editor tooling expects? Or does this not end up in the compiler log file?

Reason I ask is because we have an issue with the current setup where dependency cycles aren't reported in the editor.

**Comment by jfrolich** [comment]
Yes, what are the guidelines for the formatting the editor tools expect?
We also have to think to what module to attribute the cycle (maybe the last in the cycle), so if the cycle is `Dep01 -> Dep02 -> NS -> NewNamespace.NS_alias -> Dep01` we can attribute it to NS_alias and write it to that compiler log file.

I'll do it as a follow-up PR because I'd like to merge this

**Comment by jfrolich** [comment]
perhaps it is nicest to call out to the compiler, where we provide the compiler with the dependency that causes a cycle, then the compiler can generate an error message with line numbers etc.

**Pull request merged**
